# default: &default
#   #adapter: mysql2
#   adapter: mysql2
#   encoding: utf8mb4
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password:
#   host: localhost

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rubyoverview_development

test:
  <<: *default
  database: rubyoverview_test

production:
  <<: *default
  database: rubyoverview_production
  username: <%= Rails.application.credentials.production_db_username %>
  password: <%= Rails.application.credentials.production_db_password %>